import { Challenge } from '@/types';

export const EXERCISE_ITEMS: Challenge[] = [
  {
    id: '1',
    title: 'Day 1: Full-Body Strength Training',
    description: 'Push-ups: 3 sets of 15-20 reps\nSquats: 3 sets of 20 reps\nPlank: 3 sets, hold for 30-60 seconds\nDumbbell Rows: 3 sets of 12 reps per arm\nJumping Lunges: 2 sets of 12 reps per leg',
    calories: 350,
    type: 'exercise',
    image: require('../assets/images/exercise-item.jpg'),
    buttonText: 'View Details',
  },
  {
    id: '2',
    title: 'Day 2: Agility & Speed',
    description: 'High Knees: 3 sets of 30 seconds\nLateral Shuffles: 3 sets of 15-20 seconds\nCone Drills (zig-zag sprint): 3 rounds, 20 meters each\nBurpees: 2 sets of 12 reps\nCooldown Stretch: Focus on hip flexors and hamstrings',
    calories: 300,
    type: 'exercise',
    image: require('../assets/images/exercise-item.jpg'),
    buttonText: 'View Details',
  },
  {
    id: '3',
    title: 'Day 3: Endurance Boost',
    description: '10-minute jog or brisk walk to warm up\nSprint Intervals: 30 seconds sprint, 60 seconds walk (6 rounds)\nStair Running: 3 sets of 2 minutes each\nCooldown Walk: 5-10 minutes',
    calories: 400,
    type: 'exercise',
    image: require('../assets/images/exercise-item.jpg'),
    buttonText: 'View Details',
  },
  {
    id: '4',
    title: 'Day 4: Active Recovery',
    description: 'Yoga or Stretching: 20-30 minutes\nSide Plank: 3 sets, hold for 20-30 seconds per side\nBird Dogs: 3 sets of 10 reps per side\nFoam Rolling: Focus on calves, quads, and back',
    calories: 200,
    type: 'exercise',
    image: require('../assets/images/exercise-item.jpg'),
    buttonText: 'View Details',
  },
  {
    id: '5',
    title: 'Day 5: Plyometrics',
    description: 'Box Jumps: 3 sets of 10 reps\nBroad Jumps: 3 sets of 8 reps\nSkater Hops: 3 sets of 10 reps per side\nMedicine Ball Slams: 3 sets of 15 reps\nCooldown Stretch: Focus on quads and shoulders',
    calories: 380,
    type: 'exercise',
    image: require('../assets/images/exercise-item.jpg'),
    buttonText: 'View Details',
  },
  {
    id: '6',
    title: 'Day 6: Sport-Specific Conditioning',
    description: 'Choose a sport-like activity to simulate game movements:\n• Basketball Dribbling/Jump Shots: 20 minutes\n• Soccer Dribbling/Passing Drills: 20 minutes\n• Tennis Footwork Drills: 20 minutes',
    calories: 320,
    type: 'exercise',
    image: require('../assets/images/exercise-item.jpg'),
    buttonText: 'View Details',
  },
  {
    id: '7',
    title: 'Day 7: Restorative Recovery',
    description: 'Yoga or Pilates: 30-40 minutes\nFoam Rolling: Full body',
    calories: 150,
    type: 'exercise',
    image: require('../assets/images/exercise-item.jpg'),
    buttonText: 'View Details',
  },
]; 